---
- name: configure modules
  ldap_attrs:
    dn: "cn=module{0},cn=config"
    bind_dn: "cn=config"
    bind_pw: "{{ credentials.ldap_config_password }}"
    attributes:
      olcModuleLoad: "{0}argon2"
- name: Set password hash policy
  ldap_attrs:
    dn: "olcDatabase={-1}frontend,cn=config"
    bind_dn: "cn=config"
    bind_pw: "{{ credentials.ldap_config_password }}"
    attributes:
      olcPasswordHash: "{ARGON2}"