---
- name: delete GPG key
  rpm_key:
    state: absent
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-AlmaLinux
- name: import GPG key
  rpm_key:
    state: present
    key: https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux
- import_role:
    name: webgate-files
  when: inventory_hostname in groups['hives']
